"""Shared constants for the distributed compute system."""

PROTOCOL_VERSION = "1.0"

DEFAULT_TCP_PORT = 8765
DEFAULT_UDP_DISCOVERY_PORT = 8766
DISCOVERY_MAGIC = "DISTCOMP_DISCOVER_V1"
DISCOVERY_REPLY_MAGIC = "DISTCOMP_MASTER_V1"

HEARTBEAT_INTERVAL_SEC = 5
HEARTBEAT_TIMEOUT_SEC = 15
TASK_DEFAULT_TIMEOUT_SEC = 30

RECONNECT_BACKOFF_START = 2
RECONNECT_BACKOFF_MAX = 30

PAIRING_CODE_LENGTH = 6
TOKEN_BYTES = 32
